#pragma once

#include <uhook.hpp>

PROCESSINTERNAL_HOOK(ActorSetInitialState);
PROCESSINTERNAL_HOOK(TrPlayerControllerReceiveLocalizedMessage);
PROCESSINTERNAL_HOOK(TrPlayerControllerRovingSpectateBeginState);
PROCESSINTERNAL_HOOK(TrPlayerControllerRovingSpectateViewAPlayer);
PROCESSINTERNAL_HOOK(TrPlayerControllerInitInputSystem);
PROCESSINTERNAL_HOOK(TrPlayerControllerPlayerTick);