#pragma once

#include <uhook.hpp>

using namespace UE3;

UE3_PROCESSINTERNAL_HOOK(ActorSetInitialState);
UE3_PROCESSINTERNAL_HOOK(TrPlayerControllerReceiveLocalizedMessage);
UE3_PROCESSINTERNAL_HOOK(TrPlayerControllerRovingSpectateBeginState);
UE3_PROCESSINTERNAL_HOOK(TrPlayerControllerRovingSpectateViewAPlayer);
UE3_PROCESSINTERNAL_HOOK(TrPlayerControllerInitInputSystem);
UE3_PROCESSINTERNAL_HOOK(TrPlayerControllerPlayerTick);